In [104]:
import pandas as pd
from sklearn import datasets
from sklearn import linear_model
from sklearn.preprocessing import normalize
from sklearn.model_selection import train_test_split, cross_val_score
import numpy as np

from sklearn.metrics import log_loss, make_scorer, accuracy_score
from sklearn.preprocessing import scale
from sklearn.impute import SimpleImputer

In [2]:
open_training_labels = pd.read_csv("../data/open_train_labels.csv.bz2", parse_dates=["timestamp"], compression = "bz2")
airports = open_training_labels["airport"].unique().tolist()

In [5]:
air="katl"
possible_labels = pd.read_csv(f"{air}_possibel_config")["0"].values.tolist()
train = pd.read_csv("training_data.csv")
train = train[train["airport"] == air]
feature_cols = ["temperature", "wind_direction", "wind_speed", "wind_gust", "cloud_ceiling", "visibility", \
                 "cloud", "lightning_prob", "precip", "depart1", "deaprt2", "depart3", "depart4", \
                       "arrive1", "arrive2", "arrive3", "arrive4", "lookahead"]
for i in range(len(possible_labels)):
  feature_cols.append('cur_config_hot'+str(i))




X = train.loc[:, feature_cols]
y = train.actual_label
x_train, x_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=12)
# Some weather data is missing :(
imp = SimpleImputer(missing_values=np.nan, strategy='median')
imp = imp.fit(x_train)
x_train = imp.transform(x_train)
x_test = imp.transform(x_test)


print(f"Starting LR cross validation for {air}")
#LRG = linear_model.LogisticRegression(penalty='l2',
#   random_state = 0,solver = 'lbfgs', multi_class = 'multinomial', max_iter=100
#).fit(x_train, y_train)

#print(f"{air}Training error: "+str(LRG.score(X, y)))


#LRG = linear_model.LogisticRegression(penalty='l2',
#random_state = 0,solver = 'lbfgs', multi_class = 'multinomial', max_iter=100000)
#scores = cross_val_score(LRG, x_train, y_train, cv=2, scoring = make_scorer(log_loss, greater_is_better=True, needs_proba=True))
#print(f"{air}scores for lbfgs l2: "+ str(scores))

#LRG = linear_model.LogisticRegression(penalty='none',
#random_state = 0,solver = 'lbfgs', multi_class = 'multinomial', max_iter=1000000)
#scores = cross_val_score(LRG, x_train, y_train, cv=2, scoring = make_scorer(log_loss, greater_is_better=True, needs_proba=True))
#print(f"{air}scores for lbfgs no penalty: "+ str(scores))

Starting LR cross validation for katl


In [146]:
LRG = linear_model.LogisticRegression(penalty='l2',solver = 'lbfgs', multi_class = 'multinomial', max_iter=100000
).fit(x_train, y_train)
# print(f"{air} Training error: "+str(LRG.score(x_train, y_train)))
# log_loss(y_train, LRG.predict_proba(x_train), labels=[0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22,23,24,25])

/Users/normenyu/opt/anaconda3/lib/python3.7/site-packages/sklearn/linear_model/_logistic.py:818: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of f AND g EVALUATIONS EXCEEDS LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  extra_warning_msg=_LOGISTIC_SOLVER_CONVERGENCE_MSG,


In [157]:
y_test_onehot = []
for i in y_test:
    temp = [0]*(len(possible_labels))
    
    temp[int(i)] = 1
    y_test_onehot.append(temp)
    

In [160]:
log_loss(np.array(y_test_onehot).flatten(), predicted_probabilities.flatten())

0.04329173805179127

In [44]:
LRG.predict_proba(X)

array([[7.01962895e-03, 5.37573481e-08, 1.50404854e-02, ...,
        5.69859817e-03, 1.23489128e-02, 6.33469021e-02],
       [7.01962895e-03, 5.37573481e-08, 1.50404854e-02, ...,
        5.69859817e-03, 1.23489128e-02, 6.33469021e-02],
       [7.01962895e-03, 5.37573481e-08, 1.50404854e-02, ...,
        5.69859817e-03, 1.23489128e-02, 6.33469021e-02],
       ...,
       [1.16525594e-07, 4.72206963e-08, 3.41295373e-05, ...,
        1.21565213e-07, 6.13865578e-04, 4.82729636e-02],
       [1.16525594e-07, 4.72206963e-08, 3.41295373e-05, ...,
        1.21565213e-07, 6.13865578e-04, 4.82729636e-02],
       [1.16525594e-07, 4.72206963e-08, 3.41295373e-05, ...,
        1.21565213e-07, 6.13865578e-04, 4.82729636e-02]])

In [84]:
log_loss(y_train, pred, labels=[0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22,23,24,25])

2.55756193783863

In [15]:
LRG.classes_

array([ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11., 12.,
       13., 14., 15., 16., 17., 18., 19., 20., 21., 22., 23., 24., 26.])

In [105]:
train['cur_config_hot19'][1000:1050]

1000    1.0
1001    1.0
1002    1.0
1003    1.0
1004    1.0
1005    1.0
1006    1.0
1007    1.0
1008    0.0
1009    0.0
1010    0.0
1011    0.0
1012    0.0
1013    0.0
1014    0.0
1015    0.0
1016    0.0
1017    0.0
1018    0.0
1019    0.0
1020    1.0
1021    1.0
1022    1.0
1023    1.0
1024    1.0
1025    1.0
1026    1.0
1027    1.0
1028    1.0
1029    1.0
1030    1.0
1031    1.0
1032    1.0
1033    1.0
1034    1.0
1035    1.0
1036    1.0
1037    1.0
1038    1.0
1039    1.0
1040    1.0
1041    1.0
1042    1.0
1043    1.0
1044    1.0
1045    1.0
1046    1.0
1047    1.0
1048    1.0
1049    1.0
Name: cur_config_hot19, dtype: float64

In [103]:
y[1000:1050]

1000    19.0
1001    19.0
1002    19.0
1003    19.0
1004    19.0
1005    19.0
1006    19.0
1007    19.0
1008    19.0
1009    19.0
1010    19.0
1011    19.0
1012    19.0
1013    19.0
1014    19.0
1015    19.0
1016    19.0
1017    19.0
1018    19.0
1019    19.0
1020    19.0
1021    19.0
1022    19.0
1023    19.0
1024    19.0
1025    19.0
1026    19.0
1027    19.0
1028    19.0
1029    19.0
1030    19.0
1031    19.0
1032    19.0
1033    19.0
1034    19.0
1035    19.0
1036    19.0
1037    19.0
1038    19.0
1039    19.0
1040    19.0
1041    19.0
1042    19.0
1043    19.0
1044    19.0
1045    19.0
1046    19.0
1047    19.0
1048    19.0
1049    19.0
Name: actual_label, dtype: float64

In [95]:
cur_config = pd.read_csv(f"../data/{air}/{air}_airport_config.csv.bz2", parse_dates=["timestamp"])

In [159]:
predicted_probabilities = LRG.predict_proba(x_test).tolist()
to_add = np.setdiff1d(np.array(range(len(possible_labels))),LRG.classes_)
cur_classes = LRG.classes_
for i in range(len(predicted_probabilities)):
    for j in to_add:
        predicted_probabilities[i].insert(j, 1e-8)
        
predicted_probabilities = normalize(np.array(predicted_probabilities), axis=1, norm="l1")


In [145]:
sum(predicted_probabilities[2])

1.0000000000000002

In [26]:
cur_classes = LRG.classes_
to_add = np.setdiff1d(np.array(range(len(possible_labels))),LRG.classes_)
for j in to_add:
    cur_classes = np.insert(cur_classes, j,j)

In [27]:
cur_classes

array([ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11., 12.,
       13., 14., 15., 16., 17., 18., 19., 20., 21., 22., 23., 24., 25.,
       26.])

In [138]:
a = normalize(np.array([[1,2,3],[4,5,6]]), axis=1, norm="l1")

In [156]:
sum(abs(LRG.coef_))

array([1.19149359e+00, 1.79954258e+00, 2.04965838e+00, 3.82973605e+00,
       5.27843881e+00, 9.80658552e+00, 1.54960770e+00, 1.58740829e+01,
       2.16836497e+01, 3.55388145e-01, 4.57957762e-01, 1.55070357e+00,
       1.97002365e+00, 4.91638919e-01, 3.63872501e-01, 3.47956821e-01,
       1.12405832e+00, 1.72410951e-02, 1.65130163e+01, 2.03521016e+01,
       1.93620930e+01, 1.57218513e+01, 1.90362555e+01, 1.67204512e+01,
       1.52532985e+01, 2.16538467e+01, 1.99513865e+01, 3.58316100e+01,
       1.91544054e+01, 1.98537226e+01, 1.85536473e+01, 2.04194991e+01,
       1.07515497e+01, 1.72983840e+01, 1.59281948e+01, 2.17216169e+01,
       1.26878420e+01, 4.20048771e+01, 1.50814269e+01, 1.80410322e+01,
       1.81863183e+01, 1.77677237e+01, 2.01492828e+01, 0.00000000e+00,
       1.64152458e+01])

In [131]:
0.26726124+0.37139068+0.4472136

1.08586552

In [ ]:
feature_cols = ["temperature", "wind_direction", "wind_speed", "wind_gust", "cloud_ceiling", "visibility", \
                 "cloud", "lightning_prob", "precip", "depart1", "deaprt2", "depart3", "depart4", \
                       "arrive1", "arrive2", "arrive3", "arrive4", "lookahead"]

In [151]:
LRG.intercept_

array([-3.01868403, -1.37924348, -2.99785454,  0.18423547, -1.42511809,
        0.72719026, -1.7836876 , -1.45072199, -1.21873605,  4.53200803,
       -0.26524552,  1.18413856,  0.53675668, -2.29969727, -0.87548029,
       -1.6976047 , -0.25195893, -3.00666962,  0.23429166,  7.09421645,
       -0.29009357,  2.96554552,  0.96376875, -0.12951284,  0.25765329,
        3.41050385])

In [153]:
X

temperature  wind_direction  wind_speed  wind_gust  cloud_ceiling  \
0             69.0             7.0         8.0        0.0            8.0   
1             66.0             7.0         9.0        0.0            8.0   
2             64.0             7.0         9.0        0.0            8.0   
3             64.0             7.0         9.0        0.0            8.0   
4             64.0             7.0         9.0        0.0            8.0   
...            ...             ...         ...        ...            ...   
89131         54.0            34.0        10.0        0.0            8.0   
89132         59.0            35.0        10.0        0.0            8.0   
89133         59.0            35.0        10.0        0.0            8.0   
89134         59.0            35.0        10.0        0.0            8.0   
89135         63.0            34.0        10.0        0.0            8.0   

       visibility  cloud  lightning_prob  precip  depart1  ...  \
0             7.0    5.0             0.0     0.0     10.0  ...   
1             7.0    5.0             0.0     0.0     39.0  ...   
2             7.0    1.0             0.0     0.0     47.0  ...   
3             7.0    1.0             0.0     0.0     13.0  ...   
4             7.0    1.0             0.0     0.0     31.0  ...   
...           ...    ...             ...     ...      ...  ...   
89131         7.0    0.0             0.0     0.0     40.0  ...   
89132         7.0    0.0             0.0     0.0     43.0  ...   
89133         7.0    0.0             0.0     0.0     40.0  ...   
89134         7.0    0.0             0.0     0.0     31.0  ...   
89135         7.0    0.0             0.0     0.0     63.0  ...   

       cur_config_hot17  cur_config_hot18  cur_config_hot19  cur_config_hot20  \
0                   0.0               0.0               1.0               0.0   
1                   0.0               0.0               1.0               0.0   
2                   0.0               0.0               1.0               0.0   
3                   0.0               0.0               1.0               0.0   
4                   0.0               0.0               1.0               0.0   
...                 ...               ...               ...               ...   
89131               0.0               0.0               0.0               0.0   
89132               0.0               0.0               0.0               0.0   
89133               0.0               0.0               0.0               0.0   
89134               0.0               0.0               0.0               0.0   
89135               0.0               0.0               0.0               0.0   

       cur_config_hot21  cur_config_hot22  cur_config_hot23  cur_config_hot24  \
0                   0.0               0.0               0.0               0.0   
1                   0.0               0.0               0.0               0.0   
2                   0.0               0.0               0.0               0.0   
3                   0.0               0.0               0.0               0.0   
4                   0.0               0.0               0.0               0.0   
...                 ...               ...               ...               ...   
89131               0.0               0.0               0.0               0.0   
89132               0.0               0.0               0.0               0.0   
89133               0.0               0.0               0.0               0.0   
89134               0.0               0.0               0.0               0.0   
89135               0.0               0.0               0.0               0.0   

       cur_config_hot25  cur_config_hot26  
0                   0.0               0.0  
1                   0.0               0.0  
2                   0.0               0.0  
3                   0.0               0.0  
4                   0.0               0.0  
...                 ...               ...  
89131               0.0               0.0  
891